# Generated by Django 4.2.5 on 2023-09-26 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatapp', '0002_user_is_online_user_is_staff_alter_user_is_superuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='room_name',
            field=models.TextField(blank=True),
        ),
    ]
